# Generated by Django 4.2.1 on 2023-05-19 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_password_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='available_times',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
